"""add github integration

Revision ID: 01e0d5e494cf
Revises: b474a49f1326
Create Date: 2026-07-10 18:02:37.902583
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '01e0d5e494cf'
down_revision: str | None = 'b474a49f1326'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('default_branch', sa.String(length=80), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ahead', sa.Integer(), nullable=False),
    sa.Column('behind', sa.Integer(), nullable=False),
    sa.Column('last_commit', sa.String(length=255), nullable=False),
    sa.Column('author_initials', sa.String(length=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_pull_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('base', sa.String(length=80), nullable=False),
    sa.Column('state', sa.Enum('open', 'draft', 'merged', name='prstate'), nullable=False),
    sa.Column('checks', sa.Enum('passing', 'failing', 'pending', name='cistatus'), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('author_initials', sa.String(length=4), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_pull_requests')
    op.drop_table('repo_branches')
    op.drop_table('github_repo')
    # ### end Alembic commands ###
