"""initial schema

Revision ID: 71adaed6d60b
Revises: 
Create Date: 2026-07-10 14:11:49.381103
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '71adaed6d60b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_current_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('initials')
    )
    op.create_table('sprints',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('range', sa.String(length=80), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.Column('days_total', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('type', sa.Enum('story', 'bug', 'task', 'epic', name='issuetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'todo', 'inprogress', 'review', 'done', name='status'), nullable=False),
    sa.Column('space', sa.Enum('features', 'support', name='space'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('assignee_initials', sa.String(length=4), nullable=True),
    sa.Column('feature_key', sa.String(length=24), nullable=True),
    sa.Column('sprint_id', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('branch', sa.String(length=160), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('review_requested', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_initials'], ['members.initials'], ),
    sa.ForeignKeyConstraint(['feature_key'], ['issues.key'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_key', sa.String(length=24), nullable=False),
    sa.Column('author_initials', sa.String(length=4), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_initials'], ['members.initials'], ),
    sa.ForeignKeyConstraint(['issue_key'], ['issues.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_requests',
    sa.Column('num', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('issue_key', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=160), nullable=True),
    sa.Column('state', sa.Enum('open', 'draft', 'merged', name='prstate'), nullable=False),
    sa.Column('checks', sa.Enum('passing', 'failing', 'pending', name='cistatus'), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_key'], ['issues.key'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pr_num', sa.Integer(), nullable=False),
    sa.Column('member_initials', sa.String(length=4), nullable=False),
    sa.Column('state', sa.Enum('approved', 'pending', 'changes', name='reviewstate'), nullable=False),
    sa.ForeignKeyConstraint(['member_initials'], ['members.initials'], ),
    sa.ForeignKeyConstraint(['pr_num'], ['pull_requests.num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewers')
    op.drop_table('pull_requests')
    op.drop_table('comments')
    op.drop_table('issues')
    op.drop_table('sprints')
    op.drop_table('members')
    # ### end Alembic commands ###
