"""add inbox and calendar

Revision ID: b474a49f1326
Revises: 71adaed6d60b
Create Date: 2026-07-10 15:13:16.486584
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b474a49f1326'
down_revision: str | None = '71adaed6d60b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('meet_link', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_email', sa.String(length=160), nullable=False),
    sa.Column('sender_color', sa.String(length=9), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('preview', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('customer', 'internal', 'notification', 'newsletter', 'alert', 'meeting', name='emailcategory'), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ignore_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field', sa.Enum('sender', 'domain', 'category', 'keyword', name='ignorefield'), nullable=False),
    sa.Column('value', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_recaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_recaps')
    op.drop_table('ignore_rules')
    op.drop_table('emails')
    op.drop_table('calendar_events')
    op.drop_table('calendar_account')
    # ### end Alembic commands ###
